--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2021. 06. 07. 15:34:26
-- Server version: 5.5.5-10.4.8-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS bolt;

CREATE DATABASE bolt
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

--
-- Set default database
--
USE bolt;

--
-- Create table `fokategoria`
--
CREATE TABLE fokategoria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  foKategoriaNev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `masodlagoskategoria`
--
CREATE TABLE masodlagoskategoria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  foKategoriaID INT(11) DEFAULT NULL,
  masodlagosKategoriaNev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE masodlagoskategoria 
  ADD CONSTRAINT FK_masodlagoskategoria_foKategoria_id FOREIGN KEY (foKategoriaID)
    REFERENCES fokategoria(id) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Create table `harmadlagoskategoria`
--
CREATE TABLE harmadlagoskategoria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  masodlagoskategoriaID INT(11) DEFAULT NULL,
  harmadlagosKategoriaNev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE harmadlagoskategoria 
  ADD CONSTRAINT FK_harmadlagoskategoria_masodlagoskategoria_id FOREIGN KEY (masodlagoskategoriaID)
    REFERENCES masodlagoskategoria(id) ON DELETE CASCADE ON UPDATE NO ACTION;

--
-- Create table `tulajdonsagok`
--
CREATE TABLE tulajdonsagok (
  szekhely VARCHAR(255) DEFAULT NULL,
  utca VARCHAR(255) DEFAULT NULL,
  varos VARCHAR(255) DEFAULT NULL,
  zip VARCHAR(30) DEFAULT NULL,
  AFA DOUBLE DEFAULT NULL,
  telefon VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  facebook VARCHAR(255) DEFAULT NULL,
  adoszam VARCHAR(255) DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `markak`
--
CREATE TABLE markak (
  id INT(11) NOT NULL AUTO_INCREMENT,
  marka VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 24,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `mertekegyseg`
--
CREATE TABLE mertekegyseg (
  id INT(11) NOT NULL AUTO_INCREMENT,
  egyseg TEXT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `termek`
--
CREATE TABLE termek (
  id INT(11) NOT NULL AUTO_INCREMENT,
  termekNev VARCHAR(150) DEFAULT NULL,
  egysegArNetto INT(11) NOT NULL,
  leiras VARCHAR(255) DEFAULT NULL,
  kategoria INT(11) NOT NULL,
  mertekegysegID INT(11) NOT NULL,
  raktarKeszlet INT(11) NOT NULL,
  foto VARCHAR(255) DEFAULT NULL,
  markaID INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 28,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE termek 
  ADD CONSTRAINT FK_termek_harmadlagoskategoria_id FOREIGN KEY (kategoria)
    REFERENCES harmadlagoskategoria(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE termek 
  ADD CONSTRAINT FK_termek_markak_id FOREIGN KEY (markaID)
    REFERENCES markak(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE termek 
  ADD CONSTRAINT FK_termek_mertekegyseg_id FOREIGN KEY (mertekegysegID)
    REFERENCES mertekegyseg(id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `vasarlo`
--
CREATE TABLE vasarlo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  vezetekNev VARCHAR(255) NOT NULL,
  keresztNev VARCHAR(255) NOT NULL,
  utca VARCHAR(200) NOT NULL,
  zip VARCHAR(255) NOT NULL,
  varos VARCHAR(150) NOT NULL,
  email VARCHAR(50) NOT NULL,
  telefon VARCHAR(100) NOT NULL,
  jelszo VARCHAR(255) DEFAULT NULL,
  accessLevel TINYINT(4) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `kosar`
--
CREATE TABLE kosar (
  id INT(11) NOT NULL AUTO_INCREMENT,
  termekID INT(11) NOT NULL,
  vasarlasID INT(11) NOT NULL,
  vasarloID INT(11) NOT NULL,
  mennyiseg INT(11) NOT NULL,
  mertekEgysegID INT(11) NOT NULL,
  datum DATE NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE kosar 
  ADD CONSTRAINT FK_kosar_mertekegyseg_id FOREIGN KEY (mertekEgysegID)
    REFERENCES mertekegyseg(id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE kosar 
  ADD CONSTRAINT FK_kosar_termek_id FOREIGN KEY (termekID)
    REFERENCES termek(id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE kosar 
  ADD CONSTRAINT FK_kosar_vasarlo_id FOREIGN KEY (vasarloID)
    REFERENCES vasarlo(id) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `adatokGenerate`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE adatokGenerate()
BEGIN

DELETE
  FROM kosar;
DELETE
  FROM vasarlo;
DELETE
  FROM termek;
DELETE
  FROM mertekegyseg;
DELETE
  FROM markak;
DELETE
  FROM tulajdonsagok;
DELETE
  FROM harmadlagoskategoria;
DELETE
  FROM masodlagoskategoria;
DELETE
  FROM fokategoria;

INSERT INTO mertekegyseg
  VALUES (1, 'db'),
  (2, 'L'),
  (3, 'raklap');

INSERT INTO fokategoria
  VALUES (1, 'Háztartási gépek'),
  (2, 'Számitéstechnika'),
  (3, 'játékok');

INSERT INTO masodlagoskategoria
  VALUES (1, 1, 'Mosogépek'),
  (2, 1, 'Hűtők'),
  (3, 2, 'PC alkatrészek'),
  (4, 2, 'Perifériák'),
  (5, 3, 'Kültéri'),
  (6, 3, 'Szerep');

INSERT INTO harmadlagoskategoria
  VALUES (1, 1, 'Mosogép'),
  (2, 2, 'Borhűtő'),
  (3, 3, 'SSD'),
  (4, 3, 'Alaplapok'),
  (5, 4, 'Egerek'),
  (6, 4, 'Billenytűzet'),
  (7, 5, 'Csúszdák'),
  (8, 5, 'Hinták'),
  (9, 6, 'Gyerekkonyhák'),
  (10, 6, 'Interaktív és plüss játékok');

INSERT INTO markak
  VALUES (1, 'Kingstone'),
  (2, 'Yankee'),
  (3, 'TM Toys'),
  (4, 'Whirepool'),
  (5, 'Silverlit'),
  (6, 'Navon'),
  (7, 'MSI'),
  (8, 'Samsung'),
  (9, 'Logitech'),
  (10, 'Hyundai'),
  (11, 'White Shark'),
  (12, 'Trust'),
  (13, 'Dohany'),
  (14, 'Smoby Tefal'),
  (15, 'ROG STRIX'),
  (16, 'Stahlman'),
  (17, 'Nincs');

INSERT INTO termek
  VALUES (1, 'Lorem 3 személyses Hinta', 15000, 'lorem lipsum', 8, 1, 1, 'foto', 17),
  (2, '500 GB Kingstone', 7000, 'lorem lipsum', 3, 1, 1, 'kingstone_500.jpg', 1),
  (3, 'Yankee DH-30', 4500, 'lorem lipsum', 5, 1, 1, 'yankee_dh_30.jpg', 2),
  (4, 'TM Toys - Bianca interaktív plüss cica', 3000, 'lorem lipsum', 10, 1, 1, 'TM_Toys_Bianca_interaktiv_pluss_cica.jpg', 3),
  (5, 'Silverlit Robomancs, Az Okoskutya', 5500, 'lorem lipsum', 10, 1, 1, 'Silverlit_Robomancs_Az_Okoskutya.jpg', 5),
  (6, 'Whirlpool FWSG61283BV EE Elöltöltős keskeny mosógép, 6 kg, 1200 ford/perc', 96990, 'lorem lipsum', 1, 1, 1, 'Whirlpool_FWSG61283B.jpg', 4),
  (7, 'Navon WPR 610 AA elöltöltős mosógép, 6kg, 1000 fordulat/perc, LED kijelző', 120000, 'lorem lipsum', 1, 1, 1, 'Navon_WPR_610_AA.jpg', 6),
  (8, 'Hyundai HYUVIN12B', 32000, 'lorem lipsum', 2, 1, 1, 'Hyundai_HYUVIN12B.jpg', 10),
  (9, 'Stahlman ST-306', 37500, 'lorem lipsum', 2, 1, 1, 'Stahlman_ST-306.jpg', 16),
  (10, 'ROG STRIX B450-F GAMING AMD B450', 48000, 'lorem lipsum', 4, 1, 1, 'ROG_STRIX_B450-F_GAMING.jpg', 15),
  (11, 'MSI X470 GAMING PLUS MAX', 35000, 'lorem lipsum', 4, 1, 1, 'MSI_X470_GAMING_PLUS.jpg', 7),
  (12, 'Samsung 870 EVO', 14000, 'lorem lipsum', 3, 1, 1, 'Samsung_870_EVO.jpg', 8),
  (13, 'Logitech G102 Lightsync', 9000, 'lorem lipsum', 4, 1, 1, 'Logitech_G102_Lightsyc.jpg', 9),
  (14, 'White Shark SPARTAN', 15000, 'lorem lipsum', 6, 1, 1, 'White_Shark_SPARTAN.jpg', 11),
  (15, 'Trust 23089 GXT 865 Asta', 17000, 'lorem lipsum', 6, 1, 1, 'Trust_23089_GXT_865_Asta.jpg', 12),
  (16, 'Dohany Gyerek csúszda, 180 cm', 25000, 'lorem lipsum', 7, 1, 1, 'Dohany_Gyerek_csuszda.jpg', 13),
  (17, 'Kerti műanyag csúszda - kapaszkodóval', 20000, 'lorem lipsum', 7, 1, 1, 'Kerti_muanyag_csuszda.jpg', 17),
  (18, 'Csónak alakú fészekhinta', 17000, 'lorem lipsum', 8, 1, 1, 'Csonak_alaku_feszekhinta.jpg', 17),
  (19, 'Smoby Tefal Mikrohullámú sütő', 6000, 'lorem lipsum', 8, 1, 1, 'Smoby_Tefal_Mikrohullamu_suto.jpg', 14),
  (20, 'Timeless Tools Függőszék párnával', 12000, 'lorem lipsum', 8, 1, 1, 'Timeless_Tools_Fuggoszek.jpg', 17);

INSERT INTO tulajdonsagok (szekhely, utca, varos, zip, AFA, telefon, email, facebook, adoszam)
  VALUES ('2766 Tápiószele, Alkotás út 8.', 'Alkotás út', 'Tápiószele', '2766', 0.27, '06202131880', 'thoma.krisztian.03@gmail.com', 'www.facebook.com', '0123456789');

INSERT INTO vasarlo
  VALUES (1, 'Nagy', 'Márton', 'Kolzsnai út 8.', 3360, 'Veszprém', 'nagy.marton@gmail.com', '06302155448', '$2y$10$sKqa0Cus6rio1im1WqhHX.uMU0w.hxrQQl56/O59w8E48APOzUj0W', 1),
  (2, 'Admin', 'Márk', 'Kolzsnai út 8.', 3360, 'Cegléd', 'admin@gmail.com', '06705621664', '$2y$10$GYAyXqiywNE38X/tH/MhKuQiKRbjQOypSYCSQDlrw.U4MyI/e6VEG', 2);

INSERT INTO kosar
  VALUES (1, 2, 1, 1, 1, 1, '2020-3-9');

END
$$

DELIMITER ;

-- 
-- Dumping data for table fokategoria
--
INSERT INTO fokategoria VALUES
(1, 'Háztartási gépek'),
(2, 'Számitéstechnika'),
(3, 'játékok');

-- 
-- Dumping data for table masodlagoskategoria
--
INSERT INTO masodlagoskategoria VALUES
(1, 1, 'Mosogépek'),
(2, 1, 'Hűtők'),
(3, 2, 'PC alkatrészek'),
(4, 2, 'Perifériák'),
(5, 3, 'Kültéri'),
(6, 3, 'Szerep');

-- 
-- Dumping data for table mertekegyseg
--
INSERT INTO mertekegyseg VALUES
(1, 'db'),
(2, 'L'),
(3, 'raklap');

-- 
-- Dumping data for table markak
--
INSERT INTO markak VALUES
(1, 'Kingstone'),
(2, 'Yankee'),
(3, 'TM Toys'),
(4, 'Whirepool'),
(5, 'Silverlit'),
(6, 'Navon'),
(7, 'MSI'),
(8, 'Samsung'),
(9, 'Logitech'),
(10, 'Hyundai'),
(11, 'White Shark'),
(12, 'Trust'),
(13, 'Dohany'),
(14, 'Smoby Tefal'),
(15, 'ROG STRIX'),
(16, 'Stahlman'),
(17, 'Nincs');

-- 
-- Dumping data for table harmadlagoskategoria
--
INSERT INTO harmadlagoskategoria VALUES
(1, 1, 'Mosogép'),
(2, 2, 'Borhűtő'),
(3, 3, 'SSD'),
(4, 3, 'Alaplapok'),
(5, 4, 'Egerek'),
(6, 4, 'Billenytűzet'),
(7, 5, 'Csúszdák'),
(8, 5, 'Hinták'),
(9, 6, 'Gyerekkonyhák'),
(10, 6, 'Interaktív és plüss játékok');

-- 
-- Dumping data for table vasarlo
--
INSERT INTO vasarlo VALUES
(1, 'Nagy', 'Márton', 'Kolzsnai út 8.', '3360', 'Veszprém', 'nagy.marton@gmail.com', '06302155448', '$2y$10$sKqa0Cus6rio1im1WqhHX.uMU0w.hxrQQl56/O59w8E48APOzUj0W', 1),
(2, 'Admin', 'Márk', 'Kolzsnai út 8.', '3360', 'Cegléd', 'admin@gmail.com', '06705621664', '$2y$10$GYAyXqiywNE38X/tH/MhKuQiKRbjQOypSYCSQDlrw.U4MyI/e6VEG', 2);

-- 
-- Dumping data for table termek
--
INSERT INTO termek VALUES
(1, 'Lorem 3 személyses Hinta', 15000, 'lorem lipsum', 8, 1, 1, 'foto', 17),
(2, '500 GB Kingstone', 7000, 'lorem lipsum', 3, 1, 1, 'kingstone_500.jpg', 1),
(3, 'Yankee DH-30', 4500, 'lorem lipsum', 5, 1, 1, 'yankee_dh_30.jpg', 2),
(4, 'TM Toys - Bianca interaktív plüss cica', 3000, 'lorem lipsum', 10, 1, 1, 'TM_Toys_Bianca_interaktiv_pluss_cica.jpg', 3),
(5, 'Silverlit Robomancs, Az Okoskutya', 5500, 'lorem lipsum', 10, 1, 1, 'Silverlit_Robomancs_Az_Okoskutya.jpg', 5),
(6, 'Whirlpool FWSG61283BV EE Elöltöltős keskeny mosógép, 6 kg, 1200 ford/perc', 96990, 'lorem lipsum', 1, 1, 1, 'Whirlpool_FWSG61283B.jpg', 4),
(7, 'Navon WPR 610 AA elöltöltős mosógép, 6kg, 1000 fordulat/perc, LED kijelző', 120000, 'lorem lipsum', 1, 1, 1, 'Navon_WPR_610_AA.jpg', 6),
(8, 'Hyundai HYUVIN12B', 32000, 'lorem lipsum', 2, 1, 1, 'Hyundai_HYUVIN12B.jpg', 10),
(9, 'Stahlman ST-306', 37500, 'lorem lipsum', 2, 1, 1, 'Stahlman_ST-306.jpg', 16),
(10, 'ROG STRIX B450-F GAMING AMD B450', 48000, 'lorem lipsum', 4, 1, 1, 'ROG_STRIX_B450-F_GAMING.jpg', 15),
(11, 'MSI X470 GAMING PLUS MAX', 35000, 'lorem lipsum', 4, 1, 1, 'MSI_X470_GAMING_PLUS.jpg', 7),
(12, 'Samsung 870 EVO', 14000, 'lorem lipsum', 3, 1, 1, 'Samsung_870_EVO.jpg', 8),
(13, 'Logitech G102 Lightsync', 9000, 'lorem lipsum', 4, 1, 1, 'Logitech_G102_Lightsyc.jpg', 9),
(14, 'White Shark SPARTAN', 15000, 'lorem lipsum', 6, 1, 1, 'White_Shark_SPARTAN.jpg', 11),
(15, 'Trust 23089 GXT 865 Asta', 17000, 'lorem lipsum', 6, 1, 1, 'Trust_23089_GXT_865_Asta.jpg', 12),
(16, 'Dohany Gyerek csúszda, 180 cm', 25000, 'lorem lipsum', 7, 1, 1, 'Dohany_Gyerek_csuszda.jpg', 13),
(17, 'Kerti műanyag csúszda - kapaszkodóval', 20000, 'lorem lipsum', 7, 1, 1, 'Kerti_muanyag_csuszda.jpg', 17),
(18, 'Csónak alakú fészekhinta', 17000, 'lorem lipsum', 8, 1, 1, 'Csonak_alaku_feszekhinta.jpg', 17),
(19, 'Smoby Tefal Mikrohullámú sütő', 6000, 'lorem lipsum', 8, 1, 1, 'Smoby_Tefal_Mikrohullamu_suto.jpg', 14),
(20, 'Timeless Tools Függőszék párnával', 12000, 'lorem lipsum', 8, 1, 1, 'Timeless_Tools_Fuggoszek.jpg', 17);

-- 
-- Dumping data for table tulajdonsagok
--
INSERT INTO tulajdonsagok VALUES
('2766 Tápiószele, Alkotás út 8.', 'Alkotás út', 'Tápiószele', '2766', 0.27, '06202131880', 'thoma.krisztian.03@gmail.com', 'www.facebook.com', '0123456789');

-- 
-- Dumping data for table kosar
--
INSERT INTO kosar VALUES
(1, 2, 1, 1, 1, 1, '2020-03-09');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;